apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: thestorepw-tls
  namespace: default
spec:
  secretName: thestorepw-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: thestore.pw
  dnsNames:
    - thestore.pw